version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
  vinyl-api:
    image: gcr.io/cnsa2022-rs727/vinyl-api:latest
    container_name: vinyl-api
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TEST_MONGODB_URI=${TEST_MONGODB_URI}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}

    ports:
      - 3000:3000
    depends_on:
      - mongodb
    restart: unless-stopped
volumes:
  mongodb-data: