name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions: write-all
jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: build and test
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test
        uses: mattallty/jest-github-action@v1.0.3
        with:
          test-command: npm run coverage-gh-actions
      - uses: actions/upload-artifact@v3
        if: success() || failure() 
        with:
          name: test-results 
          path: |
            ./coverage/
      - name: Save Code Linting Report JSON
        run: npm run lint:json
        continue-on-error: true 
   
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}" 
          report-json: "./coverage/eslint-result.json"
        continue-on-error: true
  build-and-push-gcr-backend:
    name: Build & Push to GCR
    needs: [build-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_AUTH }}'
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: vinyl-api
          image_tag: latest, ${{ github.sha }}
          dockerfile: Dockerfile
          context: ./
  deploy:
    needs: [build-and-push-gcr-backend]
    runs-on: ubuntu-latest
    name: Deploy to Server
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'un-valor-para-que-no-de-error'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
            ssh ubuntu@${{ secrets.SSH_HOST }} "if [ ! -d 'vinyl-api' ]; then \
                git clone https://github.com/razvans96/vinyl-api.git; \
              else \
                cd vinyl-api && git stash && git fetch --all && git reset --hard origin/main && git pull origin main; \
              fi"
            ssh ubuntu@${{ secrets.SSH_HOST }} "cd vinyl-api && echo -e 'MONGODB_URI=${{ secrets.MONGODB_URI }}\nCLIENT_ID=${{ secrets.CLIENT_ID }}\nCLIENT_SECRET=${{ secrets.CLIENT_SECRET }}\nJWT_SECRET=${{ secrets.JWT_SECRET}}\nJWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}' > .env"
            ssh ubuntu@${{ secrets.SSH_HOST }} "cd vinyl-api && docker-compose pull && docker-compose up -d --remove-orphans && yes | docker image prune"
