name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions: write-all
jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: build and test
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test
        uses: mattallty/jest-github-action@v1.0.3
        with:
          test-command: npm run coverage-gh-actions
      - uses: actions/upload-artifact@v3
        if: success() || failure() 
        with:
          name: test-results 
          path: |
            ./coverage/
  