name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions: write-all
jobs:
  build-backend:
    runs-on: ubuntu-latest
    container: node:16-alpine
    name: build and test
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test